export const STOCK_UNIVERSE = [
  {
    code: "BHP",
    company: "BHP Group",
    sector: "Materials",
    marketCapClass: "large",
    newsSentiment: 0.31,
    blogSentiment: 0.2,
    reportSignal: 0.64,
    roeTwoYearMin: 0.23,
    epsGrowth: 0.18,
    leverageRatio: 0.42,
  },
  {
    code: "RIO",
    company: "Rio Tinto",
    sector: "Materials",
    marketCapClass: "large",
    newsSentiment: 0.26,
    blogSentiment: 0.18,
    reportSignal: 0.61,
    roeTwoYearMin: 0.21,
    epsGrowth: 0.16,
    leverageRatio: 0.36,
  },
  {
    code: "CSL",
    company: "CSL",
    sector: "Healthcare",
    marketCapClass: "large",
    newsSentiment: 0.29,
    blogSentiment: 0.19,
    reportSignal: 0.66,
    roeTwoYearMin: 0.22,
    epsGrowth: 0.17,
    leverageRatio: 0.49,
  },
  {
    code: "CBA",
    company: "Commonwealth Bank",
    sector: "Financials",
    marketCapClass: "large",
    newsSentiment: 0.21,
    blogSentiment: 0.15,
    reportSignal: 0.58,
    roeTwoYearMin: 0.19,
    epsGrowth: 0.11,
    leverageRatio: 1.18,
  },
  {
    code: "NAB",
    company: "National Australia Bank",
    sector: "Financials",
    marketCapClass: "large",
    newsSentiment: 0.16,
    blogSentiment: 0.12,
    reportSignal: 0.53,
    roeTwoYearMin: 0.18,
    epsGrowth: 0.1,
    leverageRatio: 1.22,
  },
  {
    code: "WBC",
    company: "Westpac Banking Corp",
    sector: "Financials",
    marketCapClass: "large",
    newsSentiment: 0.11,
    blogSentiment: 0.08,
    reportSignal: 0.49,
    roeTwoYearMin: 0.16,
    epsGrowth: 0.09,
    leverageRatio: 1.25,
  },
  {
    code: "MQG",
    company: "Macquarie Group",
    sector: "Financials",
    marketCapClass: "large",
    newsSentiment: 0.28,
    blogSentiment: 0.2,
    reportSignal: 0.62,
    roeTwoYearMin: 0.17,
    epsGrowth: 0.12,
    leverageRatio: 1.08,
  },
  {
    code: "WDS",
    company: "Woodside Energy",
    sector: "Energy",
    marketCapClass: "large",
    newsSentiment: 0.24,
    blogSentiment: 0.17,
    reportSignal: 0.56,
    roeTwoYearMin: 0.2,
    epsGrowth: 0.14,
    leverageRatio: 0.62,
  },
  {
    code: "STO",
    company: "Santos",
    sector: "Energy",
    marketCapClass: "large",
    newsSentiment: 0.2,
    blogSentiment: 0.14,
    reportSignal: 0.54,
    roeTwoYearMin: 0.18,
    epsGrowth: 0.13,
    leverageRatio: 0.59,
  },
  {
    code: "FMG",
    company: "Fortescue",
    sector: "Materials",
    marketCapClass: "large",
    newsSentiment: 0.27,
    blogSentiment: 0.22,
    reportSignal: 0.6,
    roeTwoYearMin: 0.24,
    epsGrowth: 0.21,
    leverageRatio: 0.35,
  },
  {
    code: "NCM",
    company: "Newcrest Mining",
    sector: "Materials",
    marketCapClass: "mid",
    newsSentiment: 0.14,
    blogSentiment: 0.1,
    reportSignal: 0.5,
    roeTwoYearMin: 0.14,
    epsGrowth: 0.08,
    leverageRatio: 0.73,
  },
  {
    code: "JHX",
    company: "James Hardie Industries",
    sector: "Industrials",
    marketCapClass: "mid",
    newsSentiment: 0.19,
    blogSentiment: 0.13,
    reportSignal: 0.55,
    roeTwoYearMin: 0.27,
    epsGrowth: 0.19,
    leverageRatio: 0.58,
  },
  {
    code: "ALL",
    company: "Aristocrat Leisure",
    sector: "Consumer Discretionary",
    marketCapClass: "large",
    newsSentiment: 0.3,
    blogSentiment: 0.24,
    reportSignal: 0.67,
    roeTwoYearMin: 0.21,
    epsGrowth: 0.16,
    leverageRatio: 0.46,
  },
  {
    code: "REA",
    company: "REA Group",
    sector: "Communication Services",
    marketCapClass: "mid",
    newsSentiment: 0.23,
    blogSentiment: 0.16,
    reportSignal: 0.59,
    roeTwoYearMin: 0.33,
    epsGrowth: 0.22,
    leverageRatio: 0.22,
  },
  {
    code: "XRO",
    company: "Xero",
    sector: "Technology",
    marketCapClass: "mid",
    newsSentiment: 0.34,
    blogSentiment: 0.26,
    reportSignal: 0.71,
    roeTwoYearMin: 0.22,
    epsGrowth: 0.24,
    leverageRatio: 0.31,
  },
  {
    code: "WTC",
    company: "WiseTech Global",
    sector: "Technology",
    marketCapClass: "mid",
    newsSentiment: 0.37,
    blogSentiment: 0.28,
    reportSignal: 0.74,
    roeTwoYearMin: 0.26,
    epsGrowth: 0.27,
    leverageRatio: 0.28,
  },
  {
    code: "COH",
    company: "Cochlear",
    sector: "Healthcare",
    marketCapClass: "mid",
    newsSentiment: 0.25,
    blogSentiment: 0.16,
    reportSignal: 0.6,
    roeTwoYearMin: 0.21,
    epsGrowth: 0.17,
    leverageRatio: 0.44,
  },
  {
    code: "RMD",
    company: "ResMed",
    sector: "Healthcare",
    marketCapClass: "large",
    newsSentiment: 0.33,
    blogSentiment: 0.25,
    reportSignal: 0.69,
    roeTwoYearMin: 0.24,
    epsGrowth: 0.2,
    leverageRatio: 0.37,
  },
  {
    code: "MIN",
    company: "Mineral Resources",
    sector: "Materials",
    marketCapClass: "small",
    newsSentiment: 0.2,
    blogSentiment: 0.14,
    reportSignal: 0.55,
    roeTwoYearMin: 0.23,
    epsGrowth: 0.18,
    leverageRatio: 0.64,
  },
  {
    code: "NST",
    company: "Northern Star Resources",
    sector: "Materials",
    marketCapClass: "small",
    newsSentiment: 0.18,
    blogSentiment: 0.13,
    reportSignal: 0.52,
    roeTwoYearMin: 0.21,
    epsGrowth: 0.16,
    leverageRatio: 0.52,
  }
];

export const EXCLUDED_SECTORS = ["Airlines", "Hospitality", "Fast Food"];
